//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterCloneMVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.TWEETs = new HashSet<TWEET>();
            this.Person1 = new HashSet<Person>();
            this.People = new HashSet<Person>();
        }
    [DisplayName("Username")]
        public string User_id { get; set; }
        [DisplayName("Password")]  
        [DataType(DataType.Password)]
        public string password { get; set; }
        [DisplayName("Full Name")]
        public string fullName { get; set; }
        [DisplayName("Email")]
        public string email { get; set; }
        [DefaultValue(DataType.DateTime)]
        public System.DateTime joined { get; set; } = System.DateTime.Now;
        [DefaultValue("true")]
        public Nullable<bool> active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TWEET> TWEETs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> Person1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> People { get; set; }
    }
}
