//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _21_WCF_Assignment_1_Task2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetJobOpenings", ReplyAction="http://tempuri.org/IService1/GetJobOpeningsResponse")]
        string[] GetJobOpenings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetJobOpenings", ReplyAction="http://tempuri.org/IService1/GetJobOpeningsResponse")]
        System.Threading.Tasks.Task<string[]> GetJobOpeningsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetJobOpeningsByRole", ReplyAction="http://tempuri.org/IService1/GetJobOpeningsByRoleResponse")]
        string[] GetJobOpeningsByRole(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetJobOpeningsByRole", ReplyAction="http://tempuri.org/IService1/GetJobOpeningsByRoleResponse")]
        System.Threading.Tasks.Task<string[]> GetJobOpeningsByRoleAsync(string value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : _21_WCF_Assignment_1_Task2.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<_21_WCF_Assignment_1_Task2.ServiceReference1.IService1>, _21_WCF_Assignment_1_Task2.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetJobOpenings() {
            return base.Channel.GetJobOpenings();
        }
        
        public System.Threading.Tasks.Task<string[]> GetJobOpeningsAsync() {
            return base.Channel.GetJobOpeningsAsync();
        }
        
        public string[] GetJobOpeningsByRole(string value) {
            return base.Channel.GetJobOpeningsByRole(value);
        }
        
        public System.Threading.Tasks.Task<string[]> GetJobOpeningsByRoleAsync(string value) {
            return base.Channel.GetJobOpeningsByRoleAsync(value);
        }
    }
}
